BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: dagger_evoenc # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 8
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc
CHECKPOINT_FOLDER: data/checkpoints/evoenc
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc
RESULTS_DIR: data/checkpoints/evoenc/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 15
  batch_size: 1
  lr: 5.0e-5
  use_iw: True
  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_NRSub_T/{split}/{split}_gt.json.gz

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: True
    lmdb_features_dir: data/trajectories_dirs/evoenc/trajectories.lmdb

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  EVOENC:
    layers: 4
    inner_dropout: 0.1
  SEQ2SEQ:
    encoder_prev_action: True
    decoder_prev_action: True
