BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: evopretrainer # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc_s2_single
CHECKPOINT_FOLDER: data/checkpoints/evoenc_s2_single
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc_s2_single
RESULTS_DIR: data/checkpoints/evoenc_s2_single/evals

PRETRAIN:
  stage: STAGE1
  excludes: ["clip_encoder","depth_encoder"]
  STAGE1:
    lr: 2.5e-4
    batch_size: 64
    epochs: 10
    loss_weights: [0.5, 0.5, 1.0]
    load_from_ckpt: False
    ckpt_to_load: data/checkpoints/evoenc_p0/ckpt.EEPolicy.4.pth

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  DEPTH_ENCODER:
    output_size: 2048 
    single_size: 128
    trainable: False
  EVOENC:
    rgb_len: 50
    layers: 4
    inner_dropout: 0.1
  CLIP:
    downsample_size: 7
    trainable: False
