BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: evopretrainer # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc_s1
CHECKPOINT_FOLDER: data/checkpoints/evoenc_s1
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc_s1/ckpt.EEPolicy.epoch0.pth
RESULTS_DIR: data/checkpoints/evoenc_s1/evals

PRETRAIN:
  stage: STAGE1
  excludes: []
  is_requeue: False
  STAGE1:
    lr: 1.0e-5
    epochs: 1
    save_steps: 10000
    batch_size: 128
    load_from_ckpt: False
    ckpt_to_load: /root/EvoEnc/data/checkpoints/evoenc_s1/ckpt.EEPolicy.step70000.pth
    loss_weights: [1.0, 1.0]

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  EVOENC:
    layers: 4
    inner_dropout: 0.1
