BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: dagger_evoenc # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc
CHECKPOINT_FOLDER: data/checkpoints/evoenc
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc
RESULTS_DIR: data/checkpoints/evoenc/evals

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 25
  batch_size: 2
  lr: 1.76e-4
  use_iw: True
  RECOLLECT_TRAINER:
    gt_file:
      data/datasets/R2R_VLNCE_NRSub_T/{split}/{split}_gt.json.gz

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/evoenc/trajectories.lmdb

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  PEAK_ATTENTION:
    use: True
    alpha: 0.4
    sigma: 0.6
  DEPTH_ENCODER:
    output_size: 2048 
    single_size: 128
  EVOENC:
    rgb_len: 10
  CLIP:
    downsample_size: 3
  SEQ2SEQ:
    encoder_prev_action: True
    decoder_prev_action: True
