BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: evopretrainer # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 1 # new version
TORCH_GPU_ID: 1
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc_s2
CHECKPOINT_FOLDER: data/checkpoints/evoenc_s2
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc_s2
RESULTS_DIR: data/checkpoints/evoenc_s2/evals

PRETRAIN:
  stage: STAGE2
  excludes: []
  is_requeue: False
  STAGE2:
    lr: 1.5e-5
    epochs: 1
    save_steps: 10000
    batch_size: 128
    load_from_ckpt: True
    ckpt_to_load: /root/EvoEnc/data/checkpoints/evoenc_s1/ckpt.EEPolicy.epoch0.pth
    loss_weights: [0.5, 0.5, 1.0]

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  EVOENC:
    layers: 4
    inner_dropout: 0.1
