BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: evopretrainer # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc_p2
CHECKPOINT_FOLDER: data/checkpoints/evoenc_p2
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc_p2
RESULTS_DIR: data/checkpoints/evoenc_p2/evals

PRETRAIN:
  stage: STAGE2
  excludes: ["clip_encoder","depth_encoder"]
  # ,"rgb_reconstruction","depth_reconstruction","inst_reconstruction","sub_reconstruction","mean_rgb_reconstruction","mean_depth_reconstruction","mean_inst_reconstruction","mean_sub_reconstruction","inner_alignment","outer_alignment"
  STAGE2:
    lr: 2.5e-5
    batch_size: 64
    epochs: 10
    loss_weights: [0.2, 0.2, 0.6, 1.0]
    load_from_ckpt: True
    ckpt_to_load: data/checkpoints/evoenc_p1/ckpt.EEPolicy.9.pth

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  DEPTH_ENCODER:
    output_size: 2048 
    single_size: 128
    trainable: False
  EVOENC:
    rgb_len: 10
    layers: 4
    inner_dropout: 0.1
    learnable_mask: True
  CLIP:
    downsample_size: 3
    trainable: False