BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_t.yaml
TRAINER_NAME: evopretrainer # dagger, or recollect_trainer
DEBUG: False
SIMULATOR_GPU_ID: 0 # new version
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 6
TENSORBOARD_DIR: data/tensorboard_dirs/evoenc_realscene_ptft
CHECKPOINT_FOLDER: data/checkpoints/evoenc_realscene_ptft
EVAL_CKPT_PATH_DIR: data/checkpoints/evoenc_realscene_ptft
RESULTS_DIR: data/checkpoints/evoenc_realscene_ptft/evals

PRETRAIN:
  stage: REALSCENE
  excludes: ["clip_encoder","depth_encoder"]
  # ,"rgb_reconstruction","depth_reconstruction","inst_reconstruction","sub_reconstruction","mean_rgb_reconstruction","mean_depth_reconstruction","mean_inst_reconstruction","mean_sub_reconstruction","inner_alignment","outer_alignment"
  STAGE3:
    lr: 1.0e-5
    batch_size: 64
    load_from_ckpt: True
    ckpt_to_load: data/checkpoints/evoenc_p2/s3.pth
    epochs: 3
    folder: "/root/autodl-tmp/realscene"

MODEL:
  policy_name: EEPolicy

  PROGRESS_MONITOR:
    use: True
    alpha: 1.0
  DEPTH_ENCODER:
    output_size: 2048 
    single_size: 128
    trainable: False
  EVOENC:
    rgb_len: 50
    layers: 4
    inner_dropout: 0.1
  CLIP:
    downsample_size: 7
    trainable: False